name: remood
description: İsin gelecegi hackathon projesi


publish_to: 'none' 


environment:
  sdk: ">=2.12.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  #Technical
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.5
  path_provider: ^2.0.1
  #Blocs
  flutter_bloc: ^7.0.0
  equatable: ^2.0.2
  get_it: ^7.1.3
  #UI Things 
  confetti: ^0.6.0-nullsafety
  carousel_slider: ^4.0.0-nullsafety.0
  flutter_form_builder: ^6.0.0-nullsafety.1
  flutter_easyloading: ^3.0.0
  line_icons: ^2.0.1
  animated_bottom_navigation_bar: ^0.3.2
  auto_size_text: ^3.0.0-nullsafety.0
  google_fonts: ^2.1.0
  #Firebase
  google_sign_in: ^5.0.3
  firebase_auth: ^1.2.0
  firebase_core: ^1.2.0
  cloud_firestore: ^2.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/stocks/
    - assets/badges/
    - assets/

